schema_version = "0.5.0"
name = "local"
log_level = "info"
domain = "local.dev"
default_replicas = 1
registry = "local.registry"

[[service]]
name = "hello-sailr"
version = "latest"
path = "hello-sailr"

[service.build]
path = "."
dockerfile = "Dockerfile"
