
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{service_name}}
  namespace: {{service_namespace}}
  annotations:
    date: {{deployment_date}}
spec:
  replicas: {{default_replicas}}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis-stack
          ports:
            - containerPort: 6379
              hostPort: 6379
            - containerPort: 8001
              hostPort: 8001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
