apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - targetPort: 6379
      port: 6379
      nodePort: 32092
    - targetPort: 8001
      port: 8001
      nodePort: 32801
  type: NodePort
