apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __PLACEHOLDER_APP_NAME__
spec:
  project: default
  source:
    repoURL: __PLACEHOLDER_REPO_URL__
    targetRevision: HEAD
    path: k8s/environments/__PLACEHOLDER_ENV__
  destination:
    server: https://kubernetes.default.svc
    namespace: __PLACEHOLDER_NAMESPACE__
