apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: kube-system
  labels:
    run: registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
  type: LoadBalancer
