[workflow.ci]
environment = "local"
mode = "check"
interactive = false
build = "disabled"
generate = "disabled"
deploy = "disabled"
report = "text"

[workflow.ci-build-plan]
environment = "local"
mode = "check"
interactive = false
build = "plan"
generate = "disabled"
deploy = "disabled"
report = "text"

[workflow.ci-generate]
environment = "local"
mode = "check"
interactive = false
build = "plan"
generate = "run"
deploy = "disabled"
report = "text"

[workflow.ci-build]
environment = "local"
mode = "build"
interactive = false
build = "run"
generate = "disabled"
deploy = "disabled"
report = "text"

[workflow.local-deploy]
environment = "local"
mode = "go"
interactive = true
build = "plan"
generate = "run"
deploy = "run"
deploy_context = "minikube"
namespace = "default"
approval = "prompt"
apply = true
report = "text"

[workflow.ci-deploy-plan]
environment = "local"
mode = "deploy"
interactive = false
build = "plan"
generate = "run"
deploy = "plan"
deploy_context = "none"
namespace = "default"
approval = "none"
apply = false
report = "both"

[workflow.staging-deploy]
environment = "staging"
mode = "deploy"
interactive = false
build = "plan"
generate = "run"
deploy = "run"
deploy_context = "staging"
namespace = "default"
approval = "external"
apply = true
report = "both"
