schema_version = "0.2.0"
name = "dev"
log_level = "INFO"
domain = "example.com"
default_replicas = 1
registry = "docker.io"
environment_variables = []

[[service_whitelist]]
name = "hello-sailr"
version = "latest"
path = "hello-sailr"

[build.rooms]
