schema_version = "0.2.0"
name = "adriftdev"
log_level = "INFO"
domain = "localhost"
default_replicas = 1
registry = "docker.io"

[[service_whitelist]]
path = "core/test"
name = "test"
version = "latest"                    # Roomservice Run in sync execution
build = "./test/service/test-service"

[build.rooms.test]
path = "./test/service/test-service"
beforeSynchronous = "bash ./scripts/init.sh"
before = "docker build . -t  localhost:5000/test:latest"
