schema_version = "0.1.0"
name = "adriftdev"
log_level = "INFO"
domain = "localhost"
default_replicas = 1
registry = "docker.io"

[[service_whitelist]]
name = "redis"
version = "latest"

[[service_whitelist]]
name = "postgres"
version = "latest"

[[service_whitelist]]
path = "core/test"
name = "test"
version = "latest"

[[service_whitelist]]
path = "core/test2"
name = "test2"
version = "latest"

[[environment_variables]]
name = "REDIS_HOST"
value = "redis"

[[environment_variables]]
name = "REDIS_PORT"
value = "6379"
