# later move env variable for the systems to here, and export them before each command.
#[[env]]
#name = "DEV_IP"
#value = 172.16.1.1

[[exec]]
type = "local"
description = "Set the minikube env to use"
command = '''minikube profile {{name}}'''

[[exec]]
type = "minikube"
description = "update host file to have the local host ip referenced"
command = '''export DEV_IP=172.16.1.1 minikube ssh "echo \"$DEV_IP registry.dev.svc.cluster.local\" | sudo tee -a /etc/hosts"'''

[[exec]]
type = "minikube"
command = "rm -rf /etc/systemd/system/multi-user.target.wants/docker.service"
description = "Remove docker systemd service file, to ensure no issues."
sudo = true

[[exec]]
type = "minikube"
sudo = true
description = "Replace docker systemd service file"
command = '''cat <<EOF
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
BindsTo=containerd.service
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket
StartLimitBurst=3
StartLimitIntervalSec=60

[Service]
Type=notify
Restart=on-failure

# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=docker --insecure-registry 10.96.0.0/12 --insecure-registry {{default_registry}}
ExecReload=/bin/kill -s HUP $MAINPID

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=processOA

[Install]
WantedBy=multi-user.target
EOF
> /etc/systemd/system/multi-user.target.wants/docker.service'''

[[exec]]
type = "minikube"
command = "systemctl daemon-reload && sudo systemctl restart docker"
description = """
Reload daemon config in systemd, and restart docker service.
"""
sudo = true
