apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-sailr
  labels:
    app: hello-sailr
    type: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-sailr
  template:
    metadata:
      labels:
        app: hello-sailr
        type: web-app
    spec:
      containers:
      - name: hello-sailr
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: hello-sailr-config
              key: NODE_ENV
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
