apiVersion: v1
kind: Service
metadata:
  name: hello-sailr
  labels:
    app: hello-sailr
    type: web-app
spec:
  selector:
    app: hello-sailr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
