
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  annotations:
    date: 2024-05-01 13:20:49
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
              hostPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
