schema_version = "0.5.0"
name = "staging"
log_level = "INFO"
domain = "staging.example.local"
default_replicas = 1
registry = "europe-west2-docker.pkg.dev/skyfleet-staging/skyfleet"

[[service]]
name = "hello-sailr"
version = "ci"
path = "hello-sailr"

[[service]]
name = "ci-build-hello"
version = "ci"
path = "examples/ci-build/hello"

[service.build]
path = "examples/ci-build/hello"
include = ["Dockerfile", "index.html"]
