apiVersion: v1
kind: Service
metadata:
  name: new-service
spec:
  selector:
    app: new-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Default, should ideally match containerPort
