schema_version = "0.2.0"
name = "{{name}}"
log_level = "INFO"
domain = "{{default_domain}}" 
default_replicas = 1
registry = "{{default_registry}}" 

service_whitelist = []

environment_variables = []

[build.rooms]
