name: Release Build and Deploy

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: sailr # Assuming 'sailr' from completion/sailr.bash

jobs:
  build_and_upload_release_assets:
    name: Build and Upload for ${{ matrix.platform.os_name }} (${{ matrix.platform.target }})
    runs-on: ${{ matrix.platform.os_runner }}
    strategy:
      matrix:
        platform:
          - os_name: Linux
            os_runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_ext: ""
            archive_ext: ".tar.gz"
    steps:
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - name: Build binary
        run: cargo build --release --locked --target ${{ matrix.platform.target }}
        # For standard Linux x86_64 builds with libssl-dev and pkg-config installed,
        # explicit OpenSSL env vars are usually not needed as pkg-config should find it.

      - name: Prepare artifact name and staging directory
        id: prep_artifact
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/v//') # Remove 'v' prefix if present
          ARTIFACT_NAME="${{ env.PROJECT_NAME }}-${VERSION}-${{ matrix.platform.target }}"
          BINARY_EXT="${{ matrix.platform.binary_ext }}" # Will be "" for Linux
          
          ARTIFACT_PATH_SUFFIX="target/${{ matrix.platform.target }}/release/${{ env.PROJECT_NAME }}${BINARY_EXT}"
          
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=./${ARTIFACT_NAME}" >> $GITHUB_ENV # Staging directory path
          echo "ARTIFACT_SOURCE_BINARY_PATH=${ARTIFACT_PATH_SUFFIX}" >> $GITHUB_ENV

          mkdir -p "./${ARTIFACT_NAME}"
          echo "Created staging directory: ./${ARTIFACT_NAME}"
        shell: bash

      - name: List files in target directory (for debugging)
        run: |
          ls -R target/${{ matrix.platform.target }}/release/
          echo "Expected binary path: ${{ env.ARTIFACT_SOURCE_BINARY_PATH }}"
        shell: bash
            
      - name: Copy files to staging directory
        run: |
          cp "${{ env.ARTIFACT_SOURCE_BINARY_PATH }}" "./${{ env.ARTIFACT_NAME }}/"
          # Attempt to copy LICENSE and README.md, ignore if they don't exist at the root
          cp LICENSE "./${{ env.ARTIFACT_NAME }}/" || echo "LICENSE file not found, skipping."
          cp README.md "./${{ env.ARTIFACT_NAME }}/" || echo "README.md file not found, skipping."
        shell: bash # Use bash for `||` operator

      - name: Package artifact (Linux)
        run: |
          tar -czvf "./${{ env.ARTIFACT_NAME }}${{ matrix.platform.archive_ext }}" -C "./${{ env.ARTIFACT_NAME }}" .
          echo "ARCHIVE_PATH=./${{ env.ARTIFACT_NAME }}${{ matrix.platform.archive_ext }}" >> $GITHUB_ENV
        shell: bash

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_PATH }}
          asset_name: ${{ env.ARTIFACT_NAME }}${{ matrix.platform.archive_ext }}
          asset_content_type: application/gzip # Changed to application/gzip for .tar.gz
