name: Sailr Workflow - ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  sailr-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Sailr
        run: cargo install --path .

      - name: Run Workflow
        run: sailr workflow run ci --non-interactive
